version: 1 
disable_existing_loggers: False    
formatters: 
    fmt1:
        format: '%(asctime)-15s : %(filename)s : %(funcName)s : %(levelname)s : %(message)s'
handlers: 
    stdout: 
        class: logging.StreamHandler 
        formatter: fmt1
        level: DEBUG 
    file:
        class: logging.FileHandler
        formatter: fmt1
        level: DEBUG
        filename: logfile.txt
root: 
    level: DEBUG
    handlers: [stdout, file]
    propagate: True
