version: 1 
disable_existing_loggers: False    
formatters: 
    fmt1:
        format: '%(module)s %(funcName)s: %(message)s'
    fmt2:
        format: '%(asctime)-15s : %(filename)s : %(funcName)s : %(levelname)s : %(message)s'
handlers: 
    stdout: 
        class: logging.StreamHandler 
        formatter: fmt2
        level: DEBUG 
    sys-logger:
        class: logging.handlers.SysLogHandler
        address: [DSHome, 514]
        formatter: fmt1
root: 
    level: DEBUG
    handlers: [stdout, sys-logger]
    propagate: True
