# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Lint with ruff
#      run: |
#        ruff check .
    - name: Get crane curves
      env:
        TOKEN: ${{ secrets.crane_curves_token }}
      run: |
        curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/akjore/crane_curves/refs/heads/main/crane_curves.yaml -o crane_curves.yaml
    - name: Test with pytest
      env:
        CRANE_CURVE_FILENAME: "crane_curves.yaml"
      run: |
        pytest
    - name: Build
      run: |
        python -m pip install --user --upgrade build
        python -m build
    - name: Configure Git
      run: |
        git config --global user.email "akjore@outlook.com"
        git config --global user.name "akj"
    - name: Commit and push wheel
      if: ${{ matrix.python-version == '3.14' }}
      run: |
        git add -f ./dist/*.whl
        git commit -m 'pushing new wheel'
        git push

  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag base
        id: tag
        run: echo "TAG_BASE=v$(date +%Y.%m.%d)" >> $GITHUB_ENV

      - name: Check if tag has already been used - add a patch number if required.
        id: check_tag
        run: |
          VERSION_PATCH=$(git tag --list "${{ env.TAG }}*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            TAG = ${{ env.TAG_BASE }}
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
            TAG = "${{ env.TAG_BASE }}-${VERSION_PATCH}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV
          
      - name: Push tag
        run: |
          git config --local user.email "akjore@outlook.com"
          git config --local user.name "akj"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
        
